$ANSIBLE_VAULT;1.1;AES256
61623831393833373438333035386231346531616566306363386364353638313631306330666630
6163636536313437653839396462613763323961663633610a623931343263653964643662666264
65653736613239376561303161626531303738653462613439366265656538626366383638666133
6466326637643937390a623662373235643664306439633134656530363832633837653037613164
37353764663135393835336339633132356336303034636635666463313463386566386231373638
3966643839353766323365343665323966323633373362383166
