$ANSIBLE_VAULT;1.1;AES256
38626234303337356563346363633036316431333138626465383535623563346164346136623937
3161363039636634623434663663326333316563613535330a626462373730356537333835613066
31396238353234363233633862646438386239353738613866373731336531636336663430636139
6365303861623362350a383364316663343563633333303831633763633662613265376365386531
31613763613336353934323161323135666432633931666661646537303331383161346331306439
3361336437616161376663326666396230386162306333333861
