- name: Delete directory
  ansible.builtin.file:
    path: {{ APPLOCATION }}
    state: absent

- name: Create a directory
  ansible.builtin.file:
    path: {{ APPLOCATION }}
    state: directory

- name: unzip backend code
  ansible.builtin.unarchive:
    src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ COMPONENT }}-v2.zip
    dest: /app
    remote_src: yes